#ifndef HALIDE_INTEGER_DIVISION_TABLE_H
#define HALIDE_INTEGER_DIVISION_TABLE_H

// Generated by find_inverse.c
namespace Halide {
namespace Internal {
namespace IntegerDivision {

extern int table_u8[64][3];
extern int table_s8[64][3];
extern int table_u16[64][3];
extern int table_s16[64][3];

}}}


#endif
