[project]
name = "halide-workspace"
version = "0"
requires-python = ">=3.10"

[tool.uv.workspace]
members = [
  "python_bindings/halide-bin",
  "python_bindings/halide-runtime",
  "python_bindings/halide",
]

[dependency-groups]
dev = ["pybind11>=2.11.1", "scikit-build-core>=1.0.3", "setuptools-scm>=8.3.1"]
apps = [
  "onnx==1.19.0; platform_machine != 'armv8l' and platform_machine != 'armv7l'",
  "protobuf>=7; platform_machine != 'armv8l' and platform_machine != 'armv7l'",
  "pytest; platform_machine != 'armv8l' and platform_machine != 'armv7l'",
]
tools = [
  "cmake>=3.28",
  "ninja>=1.11,!=1.13.0",
  "pre-commit>=4",
  "ruff>=0.12",
  "tbump>=6.11",
]
docs = [
  "sphinx>=7.2",
  "myst-parser>=3.0",
  "breathe>=4.35",
  "pydata-sphinx-theme>=0.15",
  "sphinxcontrib-video>=0.4",
  "sphinx-design>=0.6",
]
ci-base = [
  { include-group = "dev" },
  { include-group = "apps" },
  { include-group = "tools" },
]
ci-llvm-main = [{ include-group = "ci-base" }, "halide-llvm~=23.0.0.dev0"]
ci-llvm-22 = [{ include-group = "ci-base" }, "halide-llvm~=22.1.0"]
ci-llvm-21 = [{ include-group = "ci-base" }, "halide-llvm~=21.1.0"]

[tool.uv.sources]
halide-bin = { workspace = true }
halide-runtime = { workspace = true }
halide-llvm = { index = "halide" }
imageio = { index = "piwheels", marker = "platform_machine == 'armv8l' or platform_machine == 'armv7l'" }
numpy = { index = "piwheels", marker = "platform_machine == 'armv8l' or platform_machine == 'armv7l'" }
pillow = { index = "piwheels", marker = "platform_machine == 'armv8l' or platform_machine == 'armv7l'" }

[[tool.uv.index]]
name = "halide"
url = "https://pypi.halide-lang.org/simple"
explicit = true

[[tool.uv.index]]
name = "piwheels"
url = "https://piwheels.org/simple"
explicit = true

[tool.uv]
package = false
conflicts = [
  [
    { package = "halide-workspace", group = "ci-llvm-main" },
    { package = "halide-workspace", group = "ci-llvm-22" },
    { package = "halide-workspace", group = "ci-llvm-21" },
  ],
]

[tool.tbump]
github_url = "https://github.com/halide/Halide/"

[tool.tbump.version]
current = "22.0.0"
regex = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'

[tool.tbump.git]
message_template = "Bump version to {new_version}"
tag_template = "v{new_version}.dev0"

[[tool.tbump.file]]
src = "CMakeLists.txt"
search = "VERSION {current_version}"

[[tool.tbump.file]]
src = "python_bindings/CMakeLists.txt"
search = "VERSION {current_version}"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "FURB", "PERF", "RUF", "SIM", "UP"]
ignore = ["UP045", "SIM108"]
