#include "posix_allocator.cpp"
#define LINUX_CLOCK_SYSCALL_SYS_CLOCK_GETTIME 263
#include "linux_clock.cpp"
#include "posix_error_handler.cpp"
#include "write_debug_image.cpp"
#include "android_io.cpp"
#include "tracing.cpp"
#include "posix_math.cpp"
#include "posix_thread_pool.cpp"
#include "copy_to_host_noop.cpp"
