#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "$@" >&2
    exit 1
}

if [[ $# -ne 1 ]]; then
    die "Usage: $0 <Halide_TARGET>"
fi

HALIDE_TARGET="$1"
if [[ "${HALIDE_TARGET}" == "host" ]]; then
    die "Halide_TARGET=host is not valid for the iOS app build."
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

: "${Halide_ROOT:?Set Halide_ROOT in the environment to the Halide install prefix.}"
export HalideHelpers_ROOT="${Halide_ROOT}"

CMAKE="$(command -v cmake)"
: "${CMAKE:?cmake not found in PATH}"

BUILD_DIR="${SCRIPT_DIR}/Generators/build"

cmake -G Xcode -S "${SCRIPT_DIR}/Generators" -B "${BUILD_DIR}" \
    -DHalide_TARGET="${HALIDE_TARGET}"

## Write xcconfig for the native Xcode project.

cat > "${BUILD_DIR}/GeneratorPaths.xcconfig" <<EOF
// Generated by build.sh -- do not edit.

CMAKE_COMMAND = ${CMAKE}
GENERATORS_BUILD_DIR = ${BUILD_DIR}
HALIDE_INCLUDE_DIR = ${Halide_ROOT}/include
EOF

echo ""
echo "Setup complete. Open HelloiOS.xcworkspace in Xcode to build and run."
echo ""
echo "  open ${SCRIPT_DIR}/HelloiOS.xcworkspace"
echo ""