#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "$@" >&2
    exit 1
}

if [[ $# -ne 1 ]]; then
    die "Usage: $0 <Halide_TARGET>"
fi

HALIDE_TARGET="$1"
if [[ "${HALIDE_TARGET}" == "host" ]]; then
    die "Halide_TARGET=host is not valid for the iOS app build."
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

: "${CMAKE_BUILD_TYPE:=Release}"
: "${HELLOIOS_DEVELOPMENT_TEAM:=}"

: "${Halide_ROOT:?Set Halide_ROOT in the environment to the Halide install prefix.}"
export HalideHelpers_ROOT="${Halide_ROOT}"

CMAKE="$(command -v cmake)"
: "${CMAKE:?cmake not found in PATH}"

BUILD_DIR="${SCRIPT_DIR}/Generators/build"

cmake -S "${SCRIPT_DIR}/Generators" -B "${BUILD_DIR}" \
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
    -DHalide_TARGET="${HALIDE_TARGET}"

cmake --build "${BUILD_DIR}"

## Write xcconfig for the native Xcode project.

if [[ -n "${HELLOIOS_DEVELOPMENT_TEAM}" ]]; then
    CODE_SIGNING_SETTINGS=$(cat <<XCEOF
HELLOIOS_CODE_SIGNING_ALLOWED = YES
HELLOIOS_CODE_SIGN_IDENTITY = Apple Development
HELLOIOS_DEVELOPMENT_TEAM = ${HELLOIOS_DEVELOPMENT_TEAM}
XCEOF
)
else
    CODE_SIGNING_SETTINGS=$(cat <<'XCEOF'
HELLOIOS_CODE_SIGNING_ALLOWED = NO
HELLOIOS_CODE_SIGN_IDENTITY =
HELLOIOS_DEVELOPMENT_TEAM =
XCEOF
)
fi

cat > "${BUILD_DIR}/GeneratorPaths.xcconfig" <<EOF
// Generated by build.sh -- do not edit.

CMAKE_COMMAND = ${CMAKE}
GENERATORS_BUILD_DIR = ${BUILD_DIR}
HALIDE_INCLUDE_DIR = ${Halide_ROOT}/include

${CODE_SIGNING_SETTINGS}
EOF

echo ""
echo "Setup complete. Open HelloiOS.xcworkspace in Xcode to build and run."
echo ""
echo "  open ${SCRIPT_DIR}/HelloiOS.xcworkspace"
echo ""