#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

: "${Halide_ROOT:?Set Halide_ROOT in the environment to the Halide install prefix.}"
export HalideHelpers_ROOT="${Halide_ROOT}"

CMAKE="$(command -v cmake)"
: "${CMAKE:?cmake not found in PATH}"

BUILD_DIR="${SCRIPT_DIR}/Generators/build"

cmake -G Xcode -S "${SCRIPT_DIR}/Generators" -B "${BUILD_DIR}"

## Write xcconfig for the native Xcode project.

cat > "${BUILD_DIR}/GeneratorPaths.xcconfig" <<EOF
// Generated by build.sh -- do not edit.
GENERATORS_BUILD_DIR = ${BUILD_DIR}
HALIDE_INCLUDE_DIR = ${Halide_ROOT}/include
EOF

echo ""
echo "Setup complete. Open HelloiOS.xcworkspace in Xcode to build and run."
echo ""
echo "  open ${SCRIPT_DIR}/HelloiOS.xcworkspace"
echo ""
