#!/bin/bash

export TOP=`pwd`
export HL_HEXAGON_TOOLS=$TOP/llvm/install
export HL_HEXAGON_SIM_REMOTE=$TOP/Halide/src/runtime/hexagon_remote/bin/v60/hexagon_sim_remote
export HL_HEXAGON_SIM_CYCLES=1
#export HL_TARGET=host-hvx_128-debug 
export HL_TARGET=host-hvx_128

cd $TOP/Halide/apps/camera_pipe

export LD_LIBRARY_PATH=.:${TOP}/Halide/src/runtime/hexagon_remote/bin/host/:../../bin/build/tmp/:/prj/dsp/qdsp6/release/internal/branch-8.0/linux64/latest/Tools/lib/iss/ LLVM_CONFIG=${TOP}/llvm/build/bin/llvm-config 
export CCC_OVERRIDE_OPTIONS="+-save-temps"

export TIMING_ITERATIONS=2
make CXX=clang++ clean out.png

