#!/bin/bash

#export TOP=`pwd`

export ANDROID_NDK_HOME=/local/mnt/workspace/dev/sdk/2.0/Hexagon_SDK/2.0/tools/android-ndk-r10d
export ANDROID_ARM64_TOOLCHAIN=${ANDROID_NDK_HOME}/platforms/android-21/arch-arm64
#export HL_HEXAGON_TOOLS=/prj/dsp/qdsp6/release/internal/branch-8.0/linux64/latest/Tools/
#export HL_HEXAGON_TOOLS=

#cd $TOP/Halide/apps/camera_pipe

CCC_OVERRIDE_OPTIONS="+-save-temps" CXX=clang++ make -f Makefile.android clean run-android

