#!/bin/bash

i=250
# while [ -f samples/batch_${i}_0/training_output.txt ]; do
while [ $i -lt 1000 ]; do
    if [ -f samples/batch_${i}_0/training_output.txt ]; then 
        printf "%d " $i
        grep "HASAN: size of validation set" samples/batch_${i}_0/training_output.txt | tail -n1 | sed 's/^.*\(size of validation set = \<\S*\>\).*/\1/'
    fi
    i=$((i+1))
done

