cc_library(
    name = "check_call_graphs",
    srcs = ["check_call_graphs.h"],
    visibility = ["//test:__subpackages__"],  # TODO add @halide when https://github.com/bazelbuild/bazel/issues/1248 is fixed
)

filegroup(
    name = "expect_failure",
    srcs = ["expect_failure.sh"],
    visibility = ["//test:__subpackages__"],  # TODO add @halide when https://github.com/bazelbuild/bazel/issues/1248 is fixed
)

cc_library(
    name = "gpu_object_lifetime_tracker",
    srcs = ["gpu_object_lifetime_tracker.h"],
    visibility = ["//test:__subpackages__"],  # TODO add @halide when https://github.com/bazelbuild/bazel/issues/1248 is fixed
)
