


-- MACHINE GENERATED -- DO NOT EDIT
-- This schedule was automatically generated by (None)
-- for target=arch_unknown-0-os_unknown  -- NOLINT
-- with machine_params=(None)


apply_schedule_f2 = function( pipeline, target) 
    -- --- BEGIN machine-generated schedule
    f_2 = pipeline:get_func(3)
    f_1 = pipeline:get_func(2)
    f_0 = pipeline:get_func(1)
    in_ = pipeline:get_func(0)
    print("f_2.name is " .. f_2:name())
    print("prior to calling f_2:get_schedule() ")
    s = f_2:get_schedule()
    -- x = Var:new(f_2:get_schedule():dims()[0]:var())
    -- x = Var_new("x")
    print("Var is " .. tostring(Var) .. " type of Var is " .. type(Var))
    xi = Var_new("xi")
    xii = Var_new("xii")
    f_2
        :split(x, x, xi, 32, TailStrategy.ShiftInwards)
        :split(xi, xi, xii, 4, TailStrategy.ShiftInwards)
        :unroll(xi)
        :vectorize(xii)
        :compute_root()
        :reorder({xii, xi, x})
        :parallel(x)
    -- --- END machine-generated schedule
    
end

