-- --- BEGIN machine-generated schedule
consumer = pipeline:get_func(1)
producer = pipeline:get_func(0)
x = Var_new(consumer:get_schedule():dims()[1]:var())
xi = Var_new("xi")
xii = Var_new("xii")
y = Var_new(consumer:get_schedule():dims()[2]:var())
yi = Var_new("yi")
consumer
    :split(y, y, yi, 5, TailStrategy.ShiftInwards)
    :split(x, x, xi, 8, TailStrategy.ShiftInwards)
    :split(xi, xi, xii, 4, TailStrategy.ShiftInwards)
    :unroll(xi)
    :unroll(yi)
    :vectorize(xii)
    :compute_root()
    :reorder( xii, xi, yi, x, y )
    :parallel(y)
producer
    :store_in(MemoryType.Stack)
    :split(x, x, xi, 4, TailStrategy.RoundUp)
    :vectorize(xi)
    :compute_at(consumer, x)
    :reorder( xi, x, y )
-- --- END machine-generated schedule
