

-- MACHINE GENERATED -- DO NOT EDIT
-- This schedule was automatically generated by (None)
-- for target=arch_unknown-0-os_unknown  -- NOLINT
-- with machine_params=(None)


apply_schedule_ = function( pipeline, target) 
    -- No autoscheduler has been run for this Generator.

end

