/** \file 
 * Tables telling us how to do integer division
 * via fixed-point multiplication for various small
 * constants. This file is automatically generated
 * by find_inverse.c
 */
namespace Halide {
namespace Internal {
namespace IntegerDivision {

extern int64_t table_u8[254][3];
extern int64_t table_s8[254][3];
extern int64_t table_u16[254][3];
extern int64_t table_s16[254][3];
extern int64_t table_u32[254][3];
extern int64_t table_s32[254][3];

}
}
}
