#ifndef HALIDE_INTEGER_DIVISION_TABLE_H
#define HALIDE_INTEGER_DIVISION_TABLE_H

#include <cstdint>

#include "Util.h"

/** \file
 * Tables telling us how to do integer division via fixed-point
 * multiplication for various small constants. This file is
 * automatically generated by find_inverse.cpp.
 */
namespace Halide {
namespace Internal {
namespace IntegerDivision {
extern HALIDE_HIDDEN const int64_t table_u8[256][4];
extern HALIDE_HIDDEN const int64_t table_s8[256][4];
extern HALIDE_HIDDEN const int64_t table_u16[256][4];
extern HALIDE_HIDDEN const int64_t table_s16[256][4];
extern HALIDE_HIDDEN const int64_t table_u32[256][4];
extern HALIDE_HIDDEN const int64_t table_s32[256][4];
extern HALIDE_HIDDEN const int64_t table_runtime_u8[256][4];
extern HALIDE_HIDDEN const int64_t table_runtime_s8[256][4];
extern HALIDE_HIDDEN const int64_t table_runtime_u16[256][4];
extern HALIDE_HIDDEN const int64_t table_runtime_s16[256][4];
extern HALIDE_HIDDEN const int64_t table_runtime_u32[256][4];
extern HALIDE_HIDDEN const int64_t table_runtime_s32[256][4];
}  // namespace IntegerDivision
}  // namespace Internal
}  // namespace Halide

#endif
