name: Clang-Tidy
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '**.h'
      - '**.c'
      - '**.cpp'
      - 'run-clang-tidy.sh'
      - '**.clang-tidy'
      - '.github/workflows/clang-tidy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check_clang_tidy:
    if: "!contains(github.event.pull_request.labels.*.name, 'skip_buildbots')"
    name: Check clang-tidy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # We intentionally don't use VCPKG here so that we get some
      # notification that the ecosystem is moving on without us.
      - name: Install clang-tidy & dependencies
        run: brew install flatbuffers llvm@21 lld@21 pybind11 wabt

      - name: Run clang-tidy
        run: ./run-clang-tidy.sh
        env:
          CLANG_TIDY_LLVM_INSTALL_DIR: /opt/homebrew/opt/llvm@21
