name: Halide Presubmit Checks
on:
  # We don't want 'edited' (that's basically just the description, title, etc.)
  # We don't want 'review_requested' (that's redundant to the ones below for our purposes)
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check_clang_format:
    name: Check clang-format
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-21 main" | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          sudo apt-get install -y clang-format-21

      - name: Check clang-format
        run: ./run-clang-format.sh -c
        env:
          CLANG_FORMAT_LLVM_INSTALL_DIR: /usr/lib/llvm-21

  check_ruff:
    name: Check ruff
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  check_cmake_file_lists:
    name: Check CMake file lists
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - name: Run test sources check
        run: |
          check_dir() {
            local dir="$1"
            (
              cd "$dir" &&
              comm -23 \
                <(find . -maxdepth 1 -type f \( -name '*.c' -o -name '*.cpp' \) -printf '%f\n' | sort) \
                <(grep -P '^\s*#?\s*[A-Za-z0-9_.]+$' CMakeLists.txt | tr -d '# ' | sort) \
                | tee missing_files &&
              [ ! -s missing_files ]
            )
          }

          check_dir test/autoschedulers/adams2019
          check_dir test/autoschedulers/anderson2021
          check_dir test/autoschedulers/li2018
          check_dir test/autoschedulers/mullapudi2016
          check_dir test/correctness
          check_dir test/error
          check_dir test/failing_with_issue
          check_dir test/fuzz
          check_dir test/generator
          check_dir test/performance
          check_dir test/runtime
          check_dir test/warning

  check_gha_workflows:
    name: Check GitHub Actions workflows
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - name: actionlint
        uses: raven-actions/actionlint@v2