name: Ecosystem
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '**.h'
      - '**.c'
      - '**.cpp'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '.github/workflows/testing-ecosystem.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  LLVM_VERSION: 22

jobs:
  check_clang_tidy:
    if: "!contains(github.event.pull_request.labels.*.name, 'skip_buildbots')"
    name: CMake configure (simple vcpkg workflow)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Configure with vcpkg
        run: |
          uv sync --no-install-project --group ci-llvm-22
          source .venv/bin/activate
          export Halide_LLVM_ROOT="$(halide-llvm)"
          VCPKG_ROOT="$VCPKG_INSTALLATION_ROOT" cmake --preset release-vcpkg
