name: Makefile

env:
  LLVM_VERSION: '21'

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/testing-make.yml"

      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "**.cmake"
      - "vcpkg.json"
      - "vcpkg-configuration.json"

      - "doc/**"
      - "packaging/**"
      - "python_bindings/**"

      - "pyproject.toml"
      - "uv.lock"

      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "LICENSE.txt"
      - ".gitignore"
      - ".gitattributes"
      - ".gitmodules"
      - ".lldbinit"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_make:
    name: build on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - macos-15-intel

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get install -y pkg-config libpng-dev libjpeg-turbo8-dev
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install libjpeg-turbo libpng pkgconf protobuf
          fi
          uv sync --group ci-llvm-22 --no-install-project
          echo "${GITHUB_WORKSPACE}/.venv/bin" | tee -a "$GITHUB_PATH"
          echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/.venv" | tee -a "$GITHUB_ENV"
          echo "LLVM_CONFIG=$(halide-llvm --bindir)/llvm-config" | tee -a "$GITHUB_ENV"
          echo "MAKEFLAGS=-j $(getconf _NPROCESSORS_ONLN)" | tee -a "$GITHUB_ENV"

      - run: make build_tests

      - run: make test_internal
        if: ${{ !cancelled() }}

      - run: make test_correctness
        if: ${{ !cancelled() }}

      - run: make test_generator
        if: ${{ !cancelled() }}

      - run: make test_error
        if: ${{ !cancelled() }}

      - run: make test_warning
        if: ${{ !cancelled() }}

      - run: make test_apps
        if: ${{ !cancelled() }}

      - run: make test_tutorial
        if: ${{ !cancelled() }}
